apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-backend-service
  labels:
    app: {{ include "todo-chatbot.name" . }}-backend
    tier: backend
    {{- include "todo-chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "todo-chatbot.name" . }}-backend
    tier: backend