apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-frontend-service
  labels:
    app: {{ include "todo-chatbot.name" . }}-frontend
    tier: frontend
    {{- include "todo-chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "todo-chatbot.name" . }}-frontend
    tier: frontend