apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-native-arch.fullname" . }}-backend-service
  labels:
    {{- include "cloud-native-arch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "cloud-native-arch.name" . }}-backend